include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"

linter:
  rules:
    # Style
    prefer_single_quotes: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_final_in_for_each: true
    sort_child_properties_last: true
    use_full_hex_values_for_flutter_colors: true
    sized_box_for_whitespace: true

    # Safety
    avoid_print: true
    avoid_empty_else: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true
    prefer_void_to_null: true
    unnecessary_statements: true

    # Readability
    always_declare_return_types: true
    annotate_overrides: true
    avoid_unnecessary_containers: true
    prefer_is_empty: true
    prefer_is_not_empty: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_this: true
