// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuqaktcOUExWnjvFdVWI-oMGkb2FxGsdE',
    appId: '1:1082610556580:web:6445582d9b10639cbd9031',
    messagingSenderId: '1082610556580',
    projectId: 'sportexd-1bb0e',
    authDomain: 'sportexd-1bb0e.firebaseapp.com',
    storageBucket: 'sportexd-1bb0e.firebasestorage.app',
    measurementId: 'G-V30E8CJ6EJ',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8GmgvugMTakD6tEeJxSZyEFYv6Bk0T-M',
    appId: '1:1082610556580:ios:a1904fff67bc3e97bd9031',
    messagingSenderId: '1082610556580',
    projectId: 'sportexd-1bb0e',
    storageBucket: 'sportexd-1bb0e.firebasestorage.app',
    iosBundleId: 'com.sporsal.sporsal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCAITydGGuF6d2ZRbXPBntdPaUy1Dpzijo',
    appId: '1:1082610556580:android:cb8a956430f5de2fbd9031',
    messagingSenderId: '1082610556580',
    projectId: 'sportexd-1bb0e',
    storageBucket: 'sportexd-1bb0e.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCuqaktcOUExWnjvFdVWI-oMGkb2FxGsdE',
    appId: '1:1082610556580:web:76b434ad8ce16f47bd9031',
    messagingSenderId: '1082610556580',
    projectId: 'sportexd-1bb0e',
    authDomain: 'sportexd-1bb0e.firebaseapp.com',
    storageBucket: 'sportexd-1bb0e.firebasestorage.app',
    measurementId: 'G-FNFPJZ72GK',
  );

}